apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
        env: production
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
